name: Test target

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      os:
        required: true
        type: string
      target:
        required: true
        type: string
      target-name:
        required: true
        type: string

      python-version:
        required: false
        default: "3.8"
        type: string
      standard:
        required: false
        default: "false"
        type: string
      benchmark:
        required: false
        default: "false"
        type: string
      latest:
        required: false
        default: "false"
        type: string
      minimum-base-package:
        required: false
        default: "false"
        type: string
      test-py2:
        required: false
        default: "false"
        type: string

jobs:
  run:
    name: "${{ inputs.target-name }}"
    runs-on: "${{ inputs.os }}"

    steps:
    - name: Set up Windows
      if: runner.os == 'Windows'
      run: |-
        # https://github.com/actions/runner-images/issues/6561#issuecomment-1460061208
        Set-MpPreference -DisableRealtimeMonitoring $true
        # Enable disk performance counters
        diskperf -y

    - uses: actions/checkout@v3

    - name: Set up Python 2.7
      if: inputs.test-py2 == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: "2.7"

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Install ddev from local folder
      if: inputs.repo == 'core'
      run: |-
        pip install ./datadog_checks_dev[cli]
        pip install ./ddev

    - name: Install ddev from PyPI
      if: inputs.repo != 'core'
      run: pip install ddev

    - name: Configure ddev
      run: |-
        ddev config set repos.${{ inputs.repo }} .
        ddev config set repo ${{ inputs.repo }}

    - name: Prepare ${{ inputs.target }} for testing
      env:
        PYTHONUNBUFFERED: 1
        DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
        DOCKER_ACCESS_TOKEN: "${{ secrets.DOCKER_ACCESS_TOKEN }}"
        ORACLE_DOCKER_USERNAME: "${{ secrets.ORACLE_DOCKER_USERNAME }}"
        ORACLE_DOCKER_PASSWORD: "${{ secrets.ORACLE_DOCKER_PASSWORD }}"
      run: ddev ci setup ${{ inputs.target }}

    - name: Run Unit & Integration tests
      if: inputs.standard == 'true' && inputs.minimum-base-package == 'false'
      env:
        DDEV_TEST_ENABLE_TRACING: "${{ inputs.repo == 'core' && '1' || '0' }}"
      run: ddev test --cov --junit ${{ inputs.target }}

    - name: Run Unit & Integration tests with minimum version of base package
      if: inputs.standard == 'true' && inputs.minimum-base-package == 'true'
      run: ddev test --force-base-min --force-env-rebuild --junit ${{ inputs.target }}

    - name: Run E2E tests with latest base package
      if: inputs.standard == 'true' && inputs.repo == 'core'
      env:
        DD_API_KEY: "${{ secrets.DD_API_KEY }}"
      run: ddev env test --base --new-env --junit ${{ inputs.target }}

    - name: Run E2E tests
      if: inputs.standard == 'true' && inputs.repo != 'core'
      env:
        DD_API_KEY: "${{ secrets.DD_API_KEY }}"
      run: ddev env test --new-env --junit ${{ inputs.target }}

    - name: Run benchmarks
      if: inputs.benchmark == 'true'
      run: ddev test --bench --junit ${{ inputs.target }}

    - name: Run tests and verify support for the latest version
      if: inputs.latest == 'true'
      run: ddev test --latest --junit ${{ inputs.ddtrace_flag }} ${{ inputs.target }}

    - name: Run E2E tests for the latest version
      if: inputs.latest == 'true'
      env:
        DD_API_KEY: "${{ secrets.DD_API_KEY }}"
      run: ddev env test --base --new-env --junit ${{ inputs.ddtrace_flag }} ${{ inputs.target }}:latest
